#!/bin/bash
### BEGIN INIT INFO
# Provides:          fix-gdm3-autologin
# Required-Start:    
# Required-Stop:
# Should-Start:      
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Fix gdm3 autologin if alumno user doesn't exist.
### END INIT INFO

#case "$1" in
#  start)

grep "^AutomaticLoginEnable = true" /etc/gdm3/daemon.conf
if [ $? -eq 0 ]; then
	# El autologin esta activado
	USER=`grep "^AutomaticLogin =" /etc/gdm3/daemon.conf | sed -e 's/AutomaticLogin = //'`

	grep "^$USER:" /etc/passwd
	if [ ! $? -eq 0 ]; then
		# el usuario no existe, desactivar el autologin
		sed -i -e 's/AutomaticLoginEnable = true/AutomaticLoginEnable = false/' /etc/gdm3/daemon.conf
	fi
fi
#  ;;
#esac

exit 0
