#! /bin/sh
set -e

if [ "$1" = "configure" ]; then

    if [ -f /etc/xdg/autostart/marco-sombras.desktop ]; then
        echo "Eliminando marco-sombras.desktop anterior"
        rm /etc/xdg/autostart/marco-sombras.desktop
    fi

    if [ ! -e /usr/bin/mate-help ]; then
        if [ ! -L /usr/bin/mate-help ]; then
        	echo "Creando symlink de ayuda"
        	ln -s /usr/bin/huayra-visor-manual /usr/bin/mate-help
        fi
    fi
fi


#DEBHELPER#
