.\" Copyright (C) 2013 Fernando Toledo <ftoledo@docksud.com.ar>
.\"
.\" This is free software; you may redistribute it and/or modify
.\" it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2,
.\" or (at your option) any later version.
.\"
.\" This is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\"You should have received a copy of the GNU General Public License along
.\"with this program; if not, write to the Free Software Foundation, Inc.,
.\"51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
.TH huayra-chromium-master-defaults 1 "2013\-02\-22" "Huayra"
.SH NAME
huayra-chromium-master-defaults \- Set Huayra default chromium settings
.SH SYNOPSIS
.B huayra-chromium-master-defaults
.RI [ OPTION... ]
.SH DESCRIPTION
.B huayra-chromium-master-defaults
Update the master_preferences file of chromium to set the Huayra specific
options such as homepage.
.SH OPTIONS
.TP
.B huayra-chromium-master-defaults
does not have any command line switches.
.SH AUTHORS
.B huayra-chromium-master-defaults
was written by Author Fernando Toledo <ftoledo@docksud.com.ar> and others
.P
This manual page was written by Fernando Toledo <ftoledo@docksud.com.ar>,
for the Huayra project (but may be used by others).
.SH SEE ALSO
.BR "chromium" (1)


