#! /bin/sh
set -e

if [ "$1" = "configure" ]; then

  echo "Cargando opciones por defecto de docky"
  GCONF_CONFIG_SOURCE=`gconftool-2 --get-default-source`
  gconftool-2 --config-source="${GCONF_CONFIG_SOURCE}" --direct --load /etc/huayra/docky.defaults.xml >/dev/null

  echo "Estableciendo preferencias de chromium"
  #TODO: hay que hacer refactor a dpkg-divert
  huayra-chromium-master-defaults
fi

#DEBHELPER#
