#! /bin/sh
set -e

if [ "$1" = "configure" ]; then
	# 1. create group if not existing
    if ! getent group | grep -q "^microchip:" ; then
    	echo -n "Adding group microchip.."
      	addgroup --quiet --system microchip 2>/dev/null ||true
      	echo "..done"
    fi

    if [ -f /etc/dconf/db/site.d/00_conectar_settings_default ]; then
    	echo "Eliminando opciones antiguas de dconf"
	rm -f /etc/dconf/db/site.d/00_conectar_settings_default
    	dconf update
    fi
fi

#DEBHELPER#
