#! /bin/sh
set -e

#write_cache()
#{
#if [ -x /usr/bin/gtk-update-icon-cache-3.0 ]; then
#    if ! gtk-update-icon-cache-3.0 --force --quiet /usr/share/icons/gnome; then
#        echo "WARNING: icon cache generation failed"
#    fi
#fi
#}

if [ "$1" = "configure" ]; then
  dconf update

  if ! dpkg-statoverride --list --quiet "/var/www" >/dev/null; 
  then
      dpkg-statoverride --force --quiet --update \
          --add alumno www-data 0775 "/var/www"
  fi

  update-alternatives --install /usr/share/icons/huayra/axemenu/scalable/axemenu.svg start-here.svg /usr/share/icons/huayra/axemenu/scalable/axemenu.svg 10

  for SIZE in `echo 128 16 256 32 64`;
  do
      update-alternatives --slave /usr/share/icons/huayra/axemenu/${SIZE}x${SIZE}/axemenu.png start-here-${SIZE}.png /usr/share/icons/huayra/axemenu/${SIZE}x${SIZE}/axemenu.png;
  done

  #write_cache
  exit 0

fi

#DEBHELPER#
